name: Deploy to Cloud Run from Source

on:
  push:
    branches: [ "main" ]

env:
  PROJECT_ID: cj-tech-381914
  SERVICE: todo-list-test # TODO: update Cloud Run service name
  REGION: europe-west1 # TODO: update Cloud Run service region

jobs:
  deploy:
    permissions:
      contents: 'read'
      id-token: 'write'

    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Google Auth
        uses: 'google-github-actions/auth@v2'
        with:
          workload_identity_provider: projects/100auth/providers/test-todo
          service_account: todo-test@cj-tech-381914.iam.gserviceaccount.com

      - name: Deploy to Cloud Run
        uses: google-github-actions/deploy-cloudrun@v2
        with:
          service: ${{ env.SERVICE }}
          region: ${{ env.REGION }}
          source: ./

      - name: Show Output
        run: echo ${{ steps.deploy.outputs.url }}
